/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chegg.project;

public class Server {
    public static void main(String[] args) {
        System.out.println("no server implemented yet");
    }
}
